### ISSUE TITLE
DefaultJsonPatch instance not created from deserialization 

### ISSUE THREAD

**Issue by Javilete** [tbugrara/dropwizard-patch#10]
Hello,

First of all I would like to mention that this patch implementation for dropwizard is grand, good implementation and well understood but I would like to get a clarification about an issue I am facing at the moment.
Basically, it is the difference between DefaultJsonPatch and the ContextualJsonPatch. I know the what it is for each one but in my case I was trying to use the DefaultJsonPatch as an argument of my method in order that it would handle itself the whole process of patching. The issue comes that an error is thrown saying that there is a miss match in the arguments and basically it is because it creates an instance of the ContextualJsonPatch instead of the DefaultJsonPatch. The json body that is sent in the request is a set operations like the following:
    [
        {"op": "replace", "path": "/displayNameeeeee", "value": "Esmeralda"}
    ]
    
As a workaround what I do is just create an instance of it (DefaultJsonPatch) passing the list of operations from the deserialised object of ContextualJsonPatch plus the class type of my entity:

DefaultJsonPatch<User> defaultJsonPatch = new DefaultJsonPatch(patchOperations, User.class);

How could it be done using as an argument a type of DefaultJsonPatch<User>? I guess the issue comes because it gets the list operations from the parent (ContextualJsonPatch) and the other two attributes of the class are ignored (based on the annotation)
Hope I have explained myself clearly :)
Thanks very much in advance.

**Comment by tbugrara** [comment]
Thank you so much for reporting this. Turns out I had accidentally switched off the tests for DefaultJsonPatch. I'm working on resolving this right now and will comment when a working version is uploaded!

**Comment by tbugrara** [comment]
Hey Javilete, just pushed the fix. It should be available through maven as version 0.2.1 immediately, although searching for it on their website won't show up until a few hours. Thanks again for the report :) 

Let me know if you need anything else!
