### ISSUE TITLE
ContextualJsonPatch should assign the return T object to copiedContext 

### ISSUE THREAD

**Issue by Javilete** [tbugrara/dropwizard-patch#11]
Hello again,

Using the ContextualJsonPatch in which an implementation is provided for each operation type (add, replace, etc) when each corresponding method is overriden providing custom implementation, it should be assigned to the the copiedContext.
I guess, something like this:
copiedContext = replaceOperation.replace(copiedContext, path, new JsonPatchValue(operation.getValue()));

Can you please check that?

Thank you in advance.

**Comment by tariqkb** [comment]
Thanks again for the report! You can grab version 0.2.2 for the fix.
